# Generated by Django 6.0 on 2026-01-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdirector', '0001_initial'),
        ('songsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicdirector.musicdirector'),
        ),
    ]
