# Generated by Django 6.0 on 2025-12-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_is_completed_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
